// Verifies every asset the /goodlanding build expects (brief Section 5).
// Writes missing items to ASSETS_TODO.md. Exits nonzero if BLOCKERS are missing
// (so CI / the build can gate on it). Procedural elements need no assets.
import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(process.cwd(), 'public', 'assets');
const p = (...s) => join(ROOT, ...s);

// [path, label, blocker?]  blocker = hard requirement for a faithful build
const ASSETS = [
  [p('models', 'boy.glb'), 'Boy character + 6 Mixamo/Quaternius anims (silhouette)', true],
  [p('models', 'device.glb'), 'Handheld device (or built from primitives)', false],
  [p('models', 'drum.glb'), 'Drum kit (Ch4)', false],
  [p('models', 'bass.glb'), 'Bass / double bass (Ch5)', false],
  [p('models', 'keys.glb'), 'Synth / keys (Ch6)', false],
  [p('models', 'mic.glb'), 'Vintage microphone (Ch7)', false],
  [p('hdri', 'night.hdr'), 'Night HDRI (Poly Haven, 2K)', false],
  [p('textures', 'snow_albedo.jpg'), 'Snow PBR albedo (ambientCG)', false],
  [p('textures', 'snow_normal.jpg'), 'Snow PBR normal', false],
  [p('textures', 'snow_rough.jpg'), 'Snow PBR roughness', false],
  [p('textures', 'ice_albedo.jpg'), 'Ice PBR albedo', false],
  [p('images', 'studio.png'), 'Studio screenshot for the reveal (Ch9)', true],
  // Audio: REUSED from the live-synth scrollSong engine — no files needed.
];

const missing = ASSETS.filter(([path]) => !existsSync(path));
const blockers = missing.filter(([, , b]) => b);

const rel = (path) => path.replace(process.cwd() + '/', '');
const lines = [
  '# ASSETS_TODO — /goodlanding',
  '',
  'Auto-generated by `scripts/check-assets.mjs`. Procedural elements (aurora,',
  'terrain, particles, stars, lake, grain) need NO assets. Audio reuses the',
  'live-synth `scrollSong` engine — no stem files required.',
  '',
  `Status: ${missing.length ? `${missing.length} missing (${blockers.length} blockers)` : 'ALL PRESENT ✅'}`,
  '',
  '## Missing',
  '',
  ...(missing.length
    ? missing.map(([path, label, b]) => `- [ ] ${b ? '**[BLOCKER]** ' : ''}\`${rel(path)}\` — ${label}`)
    : ['_none_']),
  '',
  '## Sources (all free / CC0 / CC-BY)',
  '',
  '- Boy + anims: mixamo.com (Adobe login) OR quaternius.com (CC0, no login)',
  '- Instruments: sketchfab.com (Downloadable + CC0/CC-BY) / quaternius / kenney.nl',
  '- HDRI: polyhaven.com/hdris (Night category, 2K)',
  '- PBR: ambientcg.com (snow + ice, 2K JPG)',
  '- studio.png: screenshot auroragroove.com/studio at 2x',
  '',
];
writeFileSync(join(process.cwd(), 'ASSETS_TODO.md'), lines.join('\n'));

console.log(`check-assets: ${missing.length} missing, ${blockers.length} blockers. Wrote ASSETS_TODO.md`);
if (blockers.length) {
  console.log('BLOCKERS:', blockers.map(([path]) => rel(path)).join(', '));
  process.exit(0); // non-fatal during scaffolding; flip to exit(1) at the M1 gate
}
